# Generated by Django 4.2.4 on 2023-08-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('complain_box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='zone',
        ),
        migrations.AddField(
            model_name='institute',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complain_box.municipality', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainant_email',
            field=models.EmailField(blank=True, help_text='Enter the email address of the complainant.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainant_name',
            field=models.CharField(blank=True, help_text='Enter the name of the complainant.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainant_phone',
            field=models.CharField(blank=True, help_text='Enter the phone number of the complainant.', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainant_type',
            field=models.ForeignKey(blank=True, help_text='Select the type of complainant.', null=True, on_delete=django.db.models.deletion.CASCADE, to='complain_box.complainanttype'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complained_to',
            field=models.ForeignKey(blank=True, help_text='Select the designation of the person the complaint is addressed to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='author.designation'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='details',
            field=models.TextField(blank=True, help_text='Enter the details of the complaint.', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='institute',
            field=models.ForeignKey(blank=True, help_text='Select the institute associated with the complaint.', null=True, on_delete=django.db.models.deletion.CASCADE, to='complain_box.institute'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='Select the class of the student involved.', null=True, on_delete=django.db.models.deletion.CASCADE, to='complain_box.class'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_name',
            field=models.CharField(blank=True, help_text='Enter the name of the student involved in the complaint.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_roll',
            field=models.IntegerField(blank=True, help_text='Enter the roll number of the student.', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Select the subject or topic of the complaint.', null=True, on_delete=django.db.models.deletion.CASCADE, to='complain_box.subject'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, help_text='Enter the title of the complaint.', max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
