# Generated by Django 4.2.4 on 2023-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_box', '0002_remove_institute_zone_institute_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='priority',
            field=models.IntegerField(default=50, help_text='Set the priority any number, higher priority makes the content show first'),
        ),
        migrations.AddField(
            model_name='complainanttype',
            name='priority',
            field=models.IntegerField(default=50, help_text='Set the priority any number, higher priority makes the content show first'),
        ),
        migrations.AddField(
            model_name='institute',
            name='priority',
            field=models.IntegerField(default=50, help_text='Set the priority any number, higher priority makes the content show first'),
        ),
        migrations.AddField(
            model_name='institutetype',
            name='priority',
            field=models.IntegerField(default=50, help_text='Set the priority any number, higher priority makes the content show first'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='priority',
            field=models.IntegerField(default=50, help_text='Set the priority any number, higher priority makes the content show first'),
        ),
        migrations.AddField(
            model_name='subject',
            name='priority',
            field=models.IntegerField(default=50, help_text='Set the priority any number, higher priority makes the content show first'),
        ),
    ]
