# Generated by Django 4.2.4 on 2023-08-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_box', '0003_class_priority_complainanttype_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('solved', 'Solved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
