# Generated by Django 4.2.4 on 2023-08-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_box', '0004_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complainant_type_alt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='subject_alt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
